version: '3.8'

services:
  # PostgreSQL Database for Development
  db:
    image: postgres:14-alpine
    container_name: academia_db_dev
    restart: unless-stopped
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data/
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=academia_veritas_dev
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d academia_veritas_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - academia_dev_network

  # Python Flask Backend for Development
  backend:
    container_name: academia_backend_dev
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - backend_dev_uploads:/app/uploads
    ports:
      - "5002:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://admin:admin@db:5432/academia_veritas_dev
      - SECRET_KEY=dev-secret-key
      - INFURA_API_KEY=${INFURA_API_KEY}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - WALLET_PRIVATE_KEY=${WALLET_PRIVATE_KEY}
      - WALLET_ADDRESS=${WALLET_ADDRESS}
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "app.py"]
    networks:
      - academia_dev_network

  # Redis for Development
  redis:
    image: redis:7-alpine
    container_name: academia_redis_dev
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - academia_dev_network

volumes:
  postgres_dev_data:
    driver: local
  backend_dev_uploads:
    driver: local
  redis_dev_data:
    driver: local

networks:
  academia_dev_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
